# FastAPI server config
[mqtt]
broker =  "mqtt_broker"
port = 1883
client = "fastapi"
to_server_topic = "vehicle/1/control/to_server"
to_scooter_topic = "vehicle/1/control/to_scooter"

[database]
db_hostname= "timescaledb"
db_port= 5432
db_name= "scooter_data"
user= "api"
password= "changeme"
