#!/bin/bash

set -e


PGPASSWORD=${POSTGRES_PASSWORD} psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER bridge WITH PASSWORD '${BRIDGE_PASSWD}';
    CREATE USER grafana WITH PASSWORD '${GRAFANA_PASSWD}';
    CREATE USER api WITH PASSWORD '${API_PASSWD}';
EOSQL
