services:
  mqtt_broker:
    image: eclipse-mosquitto:2.0.18
    container_name: mosquitto-broker #MQTT Broker
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - ./broker/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    networks:
      - scooter

  timescaledb:
    image: timescale/timescaledb-ha:pg16  # Use HA variant since we need Postgis installed
    container_name: timescaledb
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./timescaledb/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    env_file: "./timescaledb/db.env"
    networks:
      - scooter

  bridge:
    build:
      context: ./mqtt-postgresql-bridge
      dockerfile: Dockerfile
    container_name: mqtt_pg_bridge
    restart: unless-stopped
    volumes:
      - ./mqtt-postgresql-bridge/config.toml:/app/config.toml:ro
    networks:
      - scooter

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: scooter_api
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./api/config.toml:/app/config.toml:ro
    networks:
      - scooter

  grafana:
    image: grafana/grafana:11.1.1
    container_name: grafana
    restart: unless-stopped
    env_file: "./grafana/grafana.env"
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards/default.yaml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./grafana/dashboards/martinete_08.json:/var/lib/grafana/dashboards/martinete_08.json
    networks:
      - scooter

networks:
  scooter:
    external: true
    driver: bridge

volumes:
  timescaledb_data:
  grafana_data:
