{
 "title": "MARTINETE",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Scooter",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "columns": [
      { "selector": "status", "text": "status", "type": "string" }
     ],
     "json_options": {
      "root_is_not_array": true
     },
     "root_selector": "$.response",
     "source": "url",
     "type": "json",
     "url": "http://scooter_api/api/v1/command/get_relay_status",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Live Speed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"speed_kmh\")",
     "rawSql": "SELECT speed_kmh FROM general_info WHERE time >= NOW() - INTERVAL '10 seconds' ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Current Trip Distance",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"trip_distance_m\")                  ",
     "rawSql": "SELECT trip_distance_m FROM general_info WHERE time >= NOW() - INTERVAL '10 seconds' ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Current Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"trip_distance_m\")                  ",
     "rawSql": "SELECT uptime_sec FROM general_info WHERE time >= NOW() - INTERVAL '10 seconds' ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Odometer ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"trip_distance_m\")                  ",
     "rawSql": "SELECT total_distance_m FROM general_info ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Battery Capacity (Latest)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mamph" } },
   "targets": [
    {
     "rawSql": "SELECT capacity FROM battery_info ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Location (Hist)",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT l.time,ST_X(ST_AsEWKT(location)) AS longitude,\n       ST_Y(ST_AsEWKT(location)) AS latitude,\n       speed_kmh\nFROM location_info l\nJOIN general_info g ON l.time = g.time \nWHERE (ST_X(ST_AsEWKT(location)) <> 0) AND (ST_Y(ST_AsEWKT(location)) <> 0) AND $__timeFilter(l.time)"
    }
   ]
  },
  {
   "title": "Estimated range left ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"trip_distance_m\")                  ",
     "rawSql": "SELECT est_distance_left_km FROM general_info ORDER BY time DESC LIMIT 1\n"
    }
   ]
  },
  {
   "title": "Battery Percent (Latest)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"battery_percent\")                  ",
     "rawSql": "SELECT percent FROM battery_info ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Speed (Hist)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"speed_kmh\")",
     "rawSql": "SELECT time,speed_kmh from general_info WHERE $__timeFilter(time) "
    }
   ]
  },
  {
   "title": "Altitude (Live)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT altitude FROM location_info WHERE time >= NOW() - INTERVAL '10 seconds' ORDER BY time DESC LIMIT 1\n"
    }
   ]
  },
  {
   "title": "Frame Temp (Live)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"trip_distance_m\")                  ",
     "rawSql": "SELECT frame_temp FROM general_info WHERE time >= NOW() - INTERVAL '10 seconds' ORDER BY time DESC LIMIT 1\n"
    }
   ]
  },
  {
   "title": "Battery Output Power (Live)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"battery_voltage\")                  ",
     "rawSql": "SELECT power FROM battery_info WHERE time >= NOW() - INTERVAL '10 seconds' ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "GPS Speed (Live)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "rawSql": "SELECT gps_speed FROM location_info WHERE time >= NOW() - INTERVAL '10 seconds' ORDER BY time DESC LIMIT 1\n"
    }
   ]
  },
  {
   "title": "Battery Temp1  (Live)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"battery_voltage\")",
     "rawSql": "SELECT temp1 FROM battery_info WHERE time >= NOW() - INTERVAL '10 seconds' ORDER BY time DESC LIMIT 1\n"
    }
   ]
  },
  {
   "title": "Battery Voltage (Live)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"battery_voltage\")                  ",
     "rawSql": "SELECT voltage FROM battery_info WHERE time >= NOW() - INTERVAL '10 seconds' ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Battery Current (Live)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "mamph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"battery_voltage\")                  ",
     "rawSql": "SELECT current FROM battery_info WHERE time >= NOW() - INTERVAL '10 seconds' ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Altitude (Hist)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"battery_percent\")",
     "rawSql": "SELECT time,altitude from location_info WHERE $__timeFilter(time)\n"
    }
   ]
  },
  {
   "title": "Battery Temp1  (Hist)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"battery_voltage\")",
     "rawSql": "SELECT time,temp1 from battery_info WHERE $__timeFilter(time)\n"
    }
   ]
  },
  {
   "title": "Battery Capacity (Hist)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "mamph" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"battery_percent\")",
     "rawSql": "SELECT time,capacity from battery_info WHERE $__timeFilter(time)\n"
    }
   ]
  },
  {
   "title": "Frame Temp  (Hist)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"battery_percent\")",
     "rawSql": "SELECT time,frame_temp from general_info WHERE $__timeFilter(time)\n"
    }
   ]
  },
  {
   "title": "Battery Current (Hist)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "mamph" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"battery_voltage\")",
     "rawSql": "SELECT time,current from battery_info WHERE $__timeFilter(time)\n"
    }
   ]
  },
  {
   "title": "Battery Percent (Hist)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"battery_percent\")",
     "rawSql": "SELECT time,percent from battery_info WHERE $__timeFilter(time) "
    }
   ]
  },
  {
   "title": "GPS speed (Hist)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"battery_percent\")",
     "rawSql": "SELECT time,altitude from location_info WHERE $__timeFilter(time)\n"
    }
   ]
  },
  {
   "title": "Battery Power Output (Hist)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "mamph" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"battery_voltage\")",
     "rawSql": "SELECT time,power from battery_info WHERE $__timeFilter(time)\n"
    }
   ]
  },
  {
   "title": "Battery Voltage (Hist)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"battery_voltage\")",
     "rawSql": "SELECT time,voltage from battery_info WHERE $__timeFilter(time)\n"
    }
   ]
  }
 ]
}