{
 "title": "MARTINETE",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Location (Latest) PENDIENTEEEEE",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT time,ST_X(ST_AsEWKT(location)) AS longitude,\n       ST_Y(ST_AsEWKT(location)) AS latitude\nFROM location_info\nWHERE (ST_X(ST_AsEWKT(location)) <> 0) AND (ST_Y(ST_AsEWKT(location)) <> 0)"
    }
   ]
  },
  { "title": "Martinete PNG", "type": "canvas", "gridPos": { "h": 8, "w": 8, "x": 12, "y": 0 } },
  {
   "title": "Battery Voltage (Hist)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"battery_voltage\")",
     "rawSql": "SELECT time,voltage from battery_info WHERE $__timeFilter(time)\n"
    }
   ]
  },
  {
   "title": "Live Speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"speed_kmh\")",
     "rawSql": "SELECT speed_kmh FROM general_info WHERE time >= NOW() - INTERVAL '10 seconds' ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Current Trip Distance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"trip_distance_m\")                  ",
     "rawSql": "SELECT trip_distance_m FROM general_info WHERE time >= NOW() - INTERVAL '10 seconds' ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Current Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"trip_distance_m\")                  ",
     "rawSql": "SELECT uptime_sec FROM general_info WHERE time >= NOW() - INTERVAL '10 seconds' ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Battery Percent (Hist)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"battery_percent\")",
     "rawSql": "SELECT time,percent from battery_info WHERE $__timeFilter(time) "
    }
   ]
  },
  {
   "title": "Odometer ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"trip_distance_m\")                  ",
     "rawSql": "SELECT total_distance_m FROM general_info ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Battery Percent (Latest)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"battery_percent\")                  ",
     "rawSql": "SELECT percent FROM battery_info ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Battery Voltage (Live)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"battery_voltage\")                  ",
     "rawSql": "SELECT voltage FROM battery_info WHERE time >= NOW() - INTERVAL '10 seconds' ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Battery Current (Hist)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"battery_voltage\")",
     "rawSql": "SELECT time,current from battery_info WHERE $__timeFilter(time)\n"
    }
   ]
  },
  {
   "title": "Estimated range left ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"trip_distance_m\")                  ",
     "rawSql": "SELECT est_distance_left_km FROM general_info ORDER BY time DESC LIMIT 1\n"
    }
   ]
  },
  {
   "title": "Speed (Hist)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"speed_kmh\")",
     "rawSql": "SELECT time,speed_kmh from general_info WHERE $__timeFilter(time) "
    }
   ]
  },
  {
   "title": "Battery Current (Live)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"battery_voltage\")                  ",
     "rawSql": "SELECT current FROM battery_info WHERE time >= NOW() - INTERVAL '10 seconds' ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Battery Capacity (Latest)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "mamph" } },
   "targets": [
    {
     "rawSql": "SELECT capacity FROM battery_info ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Battery Capacity (Hist)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "mamph" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"battery_percent\")",
     "rawSql": "SELECT time,capacity from battery_info WHERE $__timeFilter(time)\n"
    }
   ]
  },
  {
   "title": "Frame Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"trip_distance_m\")                  ",
     "rawSql": "SELECT frame_temp FROM general_info WHERE time >= NOW() - INTERVAL '10 seconds' ORDER BY time DESC LIMIT 1\n"
    }
   ]
  },
  {
   "title": "Frame Temp  (Hist)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"battery_percent\")",
     "rawSql": "SELECT time,frame_temp from general_info WHERE $__timeFilter(time)\n"
    }
   ]
  },
  {
   "title": "Battery Temp2  (Hist)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"battery_voltage\")",
     "rawSql": "SELECT time,temp2 from battery_info WHERE $__timeFilter(time)\n"
    }
   ]
  },
  {
   "title": "Battery Output Power (Live)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"battery_voltage\")                  ",
     "rawSql": "SELECT power FROM battery_info WHERE time >= NOW() - INTERVAL '10 seconds' ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Battery Power Output (Hist)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"battery_voltage\")",
     "rawSql": "SELECT time,power from battery_info WHERE $__timeFilter(time)\n"
    }
   ]
  },
  {
   "title": "Battery Temp1  (Hist)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"battery_voltage\")",
     "rawSql": "SELECT time,temp1 from battery_info WHERE $__timeFilter(time)\n"
    }
   ]
  },
  {
   "title": "Altitude (Live)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT altitude FROM location_info WHERE time >= NOW() - INTERVAL '10 seconds' ORDER BY time DESC LIMIT 1\n"
    }
   ]
  },
  {
   "title": "Altitude (Hist)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"battery_percent\")",
     "rawSql": "SELECT time,altitude from location_info WHERE $__timeFilter(time)\n"
    }
   ]
  },
  {
   "title": "GPS Speed (Live)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "rawSql": "SELECT gps_speed FROM location_info WHERE time >= NOW() - INTERVAL '10 seconds' ORDER BY time DESC LIMIT 1\n"
    }
   ]
  },
  {
   "title": "GPS speed (Hist)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"battery_percent\")",
     "rawSql": "SELECT time,altitude from location_info WHERE $__timeFilter(time)\n"
    }
   ]
  },
  {
   "title": "Battery Temp2  (Live)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"battery_voltage\")",
     "rawSql": "SELECT temp2 FROM battery_info WHERE time >= NOW() - INTERVAL '10 seconds' ORDER BY time DESC LIMIT 1\n"
    }
   ]
  },
  {
   "title": "Battery Temp1  (Live)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r[\"topic\"] == \"vehicle/1/realtime\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"battery_voltage\")",
     "rawSql": "SELECT temp1 FROM battery_info WHERE time >= NOW() - INTERVAL '10 seconds' ORDER BY time DESC LIMIT 1\n"
    }
   ]
  }
 ]
}